<a href="https://colab.research.google.com/github/VanshikaSharma19/Function_Assignment/blob/main/Copy_of_NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
#Created a 3x3 Numpy array with random number between 1 and 100
import numpy as np
arr = np.random.randint(1,100, size=(3,3))
arr

array([[67, 95, 70],
       [ 7, 63,  5],
       [20, 36, 22]])

In [ ]:
#Interchanging its rows and columns
interchange = arr.transpose()
interchange

array([[67,  7, 20],
       [95, 63, 36],
       [70,  5, 22]])

In [ ]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np
arr = np.arange(10)  #1D Numpy array with10 elements

In [ ]:
arr.reshape(2,5)  #Reshape it into 2x5 array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr.reshape(5,2)  #Reshape it into 5x2 array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
random_array = np.random.rand(4, 4)
bordered_array = np.zeros((6, 6))
bordered_array[1:5, 1:5] = random_array

print(bordered_array) # To see the output, run the code.

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.16516664 0.85013668 0.71161878 0.45261246 0.        ]
 [0.         0.30408215 0.91691338 0.59926421 0.63610697 0.        ]
 [0.         0.55480406 0.20263605 0.04861115 0.00979447 0.        ]
 [0.         0.02998944 0.94163204 0.54093639 0.93220452 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
arr=np.arange(10,60,5 ,dtype=int)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [ ]:
strings = np.array(['python', 'numpy', 'pandas'])

# Uppercase
uppercase_strings = np.char.upper(strings)
print("Uppercase:", uppercase_strings)

# Lowercase
lowercase_strings = np.char.lower(strings)
print("Lowercase:", lowercase_strings)

# Title case
titlecase_strings = np.char.title(strings)
print("Titlecase:", titlecase_strings)

# Capitalize
capitalize_strings = np.char.capitalize(strings)
print("Capitalize:", capitalize_strings)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
words = 'Tina,Mina,Ravi'
np.array(words.split(","))

array(['Tina', 'Mina', 'Ravi'], dtype='<U4')

In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Addition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)
print("\nDivision:\n", division)

Addition:
 [[ 8 10 12]
 [14 16 18]]

Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
m=np.eye(5)  #5x5 identity matrix
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.diag(m) #extracting its diagonal elements

array([1., 1., 1., 1., 1.])

In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [ ]:
random_integers = np.random.randint(0, 1000, size=100)
random_integers

array([108, 803, 942, 724, 388, 836, 564, 495, 495, 473, 875, 891, 753,
       999, 866, 872, 591, 711, 471, 304, 549,  21, 622, 742, 403, 801,
       736, 252, 132, 468,   5, 898, 189, 166, 189, 459, 298, 354, 366,
       604, 651, 496, 439, 589, 805,  68, 486, 510,  32, 438, 705,  41,
       678, 202,  76, 317, 918, 382, 162, 727, 544, 733, 934, 585, 811,
       874, 664, 699, 270, 776, 952, 211, 938, 462, 905, 488, 299, 642,
       559, 628, 548, 936, 659, 783, 227, 680, 773, 374, 889, 526,  14,
       264, 738, 171,  34, 193, 790, 695, 561, 791])

In [ ]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True


prime_numbers = [num for num in random_integers if is_prime(num)]
print("Prime numbers:", prime_numbers)

Prime numbers: [5, 439, 41, 317, 727, 733, 811, 211, 659, 227, 773, 193]


In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
daily_temperatures = np.random.randint(60, 100, size=30)
daily_temperatures

array([73, 93, 78, 83, 70, 85, 70, 90, 65, 81, 73, 63, 69, 90, 77, 96, 86,
       76, 98, 87, 75, 63, 79, 94, 93, 88, 80, 77, 89, 78])

In [ ]:
weekly_averages = []
for i in range(0, len(daily_temperatures), 7):
    weekly_avg = np.mean(daily_temperatures[i:i + 7])
    weekly_averages.append(weekly_avg)

weekly_averages = np.array(weekly_averages)
weekly_averages

array([78.85714286, 75.85714286, 85.        , 82.        , 83.5       ])